#!/usr/bin/env bash
set -euo pipefail

REPO_URL_DEFAULT="git@github.com:JasonShui716/remote-codexapp.git"
REPO_URL="${REPO_URL_DEFAULT}"
GIT_BRANCH="${GIT_BRANCH:-main}"
APP_DIR="${APP_DIR:-/opt/remote-codexapp}"
NGINX_PATH="${NGINX_PATH:-/codex}"
DOMAIN="${DOMAIN:-}"
APP_PORT="${APP_PORT:-18888}"
SERVICE_NAME="${SERVICE_NAME:-codex-remoteapp}"
APP_USER="${APP_USER:-$(id -un)}"
APP_GROUP="${APP_GROUP:-${APP_USER}}"
SKIP_NGINX="${SKIP_NGINX:-0}"
SKIP_SERVICE="${SKIP_SERVICE:-0}"

SCRIPT_NAME="$(basename "$0")"

usage() {
  cat <<EOF
Usage: $SCRIPT_NAME [options]

Quick deploy + install:
  --repo <url>       Git repo URL (default: ${REPO_URL_DEFAULT})
  --dir <path>       App install directory (default: ${APP_DIR})
  --branch <name>    Git branch/tag (default: ${GIT_BRANCH})
  --domain <name>    Nginx server_name (default: prompt in interactive mode, _ for wildcard)
  --path <nginx>     Public app path, e.g. /codex (default: ${NGINX_PATH})
  --port <number>    Backend port (default: ${APP_PORT})
  --user <name>      Service run user (default: ${APP_USER})
  --skip-nginx       Skip nginx config/reload
  --skip-service     Skip systemd service install/restart
  -h, --help         Show help

Examples:
  $SCRIPT_NAME --repo ${REPO_URL_DEFAULT} --dir /opt/remote-codexapp --domain example.com
EOF
}

log() {
  echo "[deploy] $*"
}

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "required command not found: $cmd" >&2
    exit 1
  fi
}

ensure_root_cmd() {
  if [[ "${EUID}" -ne 0 ]]; then
    if ! command -v sudo >/dev/null 2>&1; then
      echo "please run as root, or install sudo for root-required steps" >&2
      exit 1
    fi
    SUDO="sudo"
  else
    SUDO=""
  fi
}

ensure_env_value() {
  local env_file="$1"
  local key="$2"
  local value="$3"
  if grep -q "^${key}=" "$env_file" 2>/dev/null; then
    sed -i "s|^${key}=.*$|${key}=${value}|" "$env_file"
  else
    printf '%s=%s\n' "$key" "$value" >> "$env_file"
  fi
}

remove_existing_nginx_codex_bindings() {
  local dir="$1"
  local target="$2"
  local ts
  ts="$(date +%Y%m%d_%H%M%S)"
  local current_conf

  if [[ ! -d "$dir" ]]; then
    return
  fi

  while IFS= read -r current_conf; do
    [[ -f "$current_conf" ]] || continue
    if grep -Fq "location ${target}" "$current_conf" ; then
      if [[ "$current_conf" == *"${SERVICE_NAME}.conf" ]]; then
        continue;
      fi
      log "Removing existing ${target} path binding in ${current_conf} (backup created)."
      cp "$current_conf" "${current_conf}.bak.${ts}"
      rm -f "$current_conf"
    fi
  done < <(find "$dir" -maxdepth 1 -type f 2>/dev/null || true)
}

build_nginx_conf() {
  local out="$1"
  local host="$2"
  local path="$3"
  local port="$4"
  local timestamp
  timestamp="$(date +%Y%m%d_%H%M%S)"
  mkdir -p "$(dirname "$out")"
  cat <<EOF >"$out"
server {
  listen 80;
  server_name ${host};
  client_max_body_size 32m;

  location = ${path} {
    return 301 ${path}/;
  }

  location ${path}/ {
    rewrite ^${path}/(.*)$ /$1 break;
    proxy_pass http://127.0.0.1:${port};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header Connection "";
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_buffering off;
  }
}

# Generated by scripts/deploy-remote.sh at ${timestamp}
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)
      REPO_URL="$2"
      shift 2
      ;;
    --dir)
      APP_DIR="$2"
      shift 2
      ;;
    --branch)
      GIT_BRANCH="$2"
      shift 2
      ;;
    --domain)
      DOMAIN="$2"
      shift 2
      ;;
    --path)
      NGINX_PATH="$2"
      shift 2
      ;;
    --port)
      APP_PORT="$2"
      shift 2
      ;;
    --user)
      APP_USER="$2"
      APP_GROUP="$2"
      shift 2
      ;;
    --skip-nginx)
      SKIP_NGINX=1
      shift
      ;;
    --skip-service)
      SKIP_SERVICE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ ! "${APP_PORT}" =~ ^[0-9]+$ ]]; then
  echo "port must be numeric: ${APP_PORT}" >&2
  exit 1
fi

if [[ "$SKIP_NGINX" != "1" && -z "${DOMAIN}" ]]; then
  if [[ -t 0 && -t 1 ]]; then
    read -r -p "Enter domain for nginx server_name (or blank for _): " domain_input
    DOMAIN="${domain_input:-_}"
  else
    echo "DOMAIN is required unless SKIP_NGINX=1" >&2
    exit 1
  fi
fi

require_cmd git
require_cmd npm
if [[ "$SKIP_SERVICE" != "1" ]]; then
  require_cmd systemctl
fi
if [[ "$SKIP_NGINX" != "1" ]]; then
  require_cmd nginx
  require_cmd systemctl
fi

APP_DIR="${APP_DIR%/}"
ENV_FILE="${APP_DIR}/server/.env"

if [[ -d "$APP_DIR" ]]; then
  log "Updating existing checkout: $APP_DIR"
  git -C "$APP_DIR" fetch --all --prune
  git -C "$APP_DIR" checkout "$GIT_BRANCH"
  if git -C "$APP_DIR" rev-parse --verify "origin/${GIT_BRANCH}" >/dev/null 2>&1; then
    git -C "$APP_DIR" pull --ff-only "origin" "$GIT_BRANCH"
  fi
else
  log "Cloning ${REPO_URL} to ${APP_DIR}"
  git clone --depth 1 --branch "$GIT_BRANCH" "$REPO_URL" "$APP_DIR"
fi

log "Installing dependencies and building web bundle"
(cd "$APP_DIR" && npm install && npm run build)

if [[ ! -f "$ENV_FILE" ]]; then
  cp "$APP_DIR/server/.env.example" "$ENV_FILE"
fi

ensure_env_value "$ENV_FILE" "HOST" "127.0.0.1"
ensure_env_value "$ENV_FILE" "PORT" "$APP_PORT"
ensure_env_value "$ENV_FILE" "CODEX_CWD" "$APP_DIR"

if [[ "$SKIP_SERVICE" != "1" ]]; then
  ensure_root_cmd
  SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
  NPM_BIN="$(command -v npm)"
  if ! id "$APP_USER" >/dev/null 2>&1; then
    echo "Service user not found: ${APP_USER}" >&2
    exit 1
  fi
  cat > /tmp/"${SERVICE_NAME}.service" <<EOF
[Unit]
Description=Codex Remote App
After=network.target

[Service]
Type=simple
User=${APP_USER}
Group=${APP_GROUP}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${ENV_FILE}
Restart=always
RestartSec=3
ExecStart=${NPM_BIN} start
StandardOutput=append:/var/log/${SERVICE_NAME}.log
StandardError=append:/var/log/${SERVICE_NAME}.error.log

[Install]
WantedBy=multi-user.target
EOF
  ${SUDO:-} mv /tmp/"${SERVICE_NAME}.service" "$SERVICE_FILE"
  ${SUDO:-} chown root:root "$SERVICE_FILE"
  ${SUDO:-} chmod 0644 "$SERVICE_FILE"
  ${SUDO:-} systemctl daemon-reload
  ${SUDO:-} systemctl enable "${SERVICE_NAME}"
  ${SUDO:-} systemctl restart "${SERVICE_NAME}"
  log "Service ${SERVICE_NAME} restarted."
fi

if [[ "$SKIP_NGINX" != "1" ]]; then
  ensure_root_cmd
  TARGET_DIR=""
  if [[ -d /etc/nginx/sites-enabled ]]; then
    remove_existing_nginx_codex_bindings "/etc/nginx/sites-enabled" "$NGINX_PATH"
    remove_existing_nginx_codex_bindings "/etc/nginx/sites-available" "$NGINX_PATH"
    TARGET_DIR="/etc/nginx/sites-available"
    CONF_PATH="${TARGET_DIR}/${SERVICE_NAME}.conf"
    build_nginx_conf "$CONF_PATH" "$DOMAIN" "$NGINX_PATH" "$APP_PORT"
    if [[ ! -L /etc/nginx/sites-enabled/${SERVICE_NAME}.conf ]]; then
      ${SUDO:-} ln -sfn "${CONF_PATH}" "/etc/nginx/sites-enabled/${SERVICE_NAME}.conf"
    else
      ${SUDO:-} ln -sfn "${CONF_PATH}" "/etc/nginx/sites-enabled/${SERVICE_NAME}.conf"
    fi
  elif [[ -d /etc/nginx/conf.d ]]; then
    remove_existing_nginx_codex_bindings "/etc/nginx/conf.d" "$NGINX_PATH"
    TARGET_DIR="/etc/nginx/conf.d"
    CONF_PATH="${TARGET_DIR}/${SERVICE_NAME}.conf"
    build_nginx_conf "$CONF_PATH" "$DOMAIN" "$NGINX_PATH" "$APP_PORT"
  else
    echo "Could not locate nginx config directory." >&2
    exit 1
  fi

  ${SUDO:-} chown root:root "$CONF_PATH"
  ${SUDO:-} chmod 0644 "$CONF_PATH"
  if ${SUDO:-} nginx -t; then
    ${SUDO:-} systemctl reload nginx
  else
    echo "nginx config check failed." >&2
    exit 1
  fi
  log "Nginx configured at ${NGINX_PATH} and reloaded."
fi

log "Done."
if [[ "$SKIP_NGINX" != "1" ]]; then
  log "Visit: http://${DOMAIN}${NGINX_PATH}"
fi
